### ISSUE TITLE
Refactored

### ISSUE THREAD

**Issue by fembiba** [kostya-alch/Miner-game#1]
# Описание 

Я кость тебе тут написал что на примере этого класса у тебя тут не так.

# Исправления

Нет пустой линии между конструктором и полями

https://github.com/kostya-alch/Miner-game/blob/c588266875c843195b753346e66d3720f1fd388e/Miner-game/Form1.cs#L18-L19

#

Поля класса всегда должны быть приватными, так же по конвенции перед их именем должно быть нижнее подчеркивание

Кроме того коментарии делаются с помощью тега summary, стобы ide понимала при наведение на поле что это описание поля. Это можно быстро создать написав пере название поля, метода, класса и тд три слеша `///`. После этого ide сгенерирует комментарий.

Некоторые переменные не правильно отображают их суть а некоторые по наваниею можно сократить

https://github.com/kostya-alch/Miner-game/blob/c588266875c843195b753346e66d3720f1fd388e/Miner-game/Form1.cs#L15-L18

Исправленное
```C#
	/// <summary>
	/// Ширина столбца поля.
	/// </summary>
        private int _width = 10;

	/// <summary>
	/// Высота столбца поля.
	/// </summary>
        private int _height = 10;

	/// <summary>
	/// Расстояние между каждой кнопкой.
	/// </summary>
        private int _distanceBetweenButtons = 35;


	/// <summary>
	/// Массив кнопок.
	/// </summary>
        private ButtonExented[,] _buttons;
```

Так же я смотрю что некоторые поля не изменяемые. Их стоит сделать или константами или `readonly`

Исправленное readonly
```C#
	/// <summary>
	/// Ширина столбца поля.
	/// </summary>
        private readonly int _width = 10;

	/// <summary>
	/// Высота столбца поля.
	/// </summary>
        private readonly int _height = 10;

	/// <summary>
	/// Расстояние между каждой кнопкой.
	/// </summary>
        private readonly int _distanceBetweenButtons = 35;


	/// <summary>
	/// Массив кнопок.
	/// </summary>
        private ButtonExented[,] _buttons;
```

Исправленное const
```C#
	/// <summary>
	/// Ширина столбца поля.
	/// </summary>
        private const int Width = 10;

	/// <summary>
	/// Высота столбца поля.
	/// </summary>
        private const int Height = 10;

	/// <summary>
	/// Расстояние между каждой кнопкой.
	/// </summary>
        private const int DistanceBetweenButtons = 35;


	/// <summary>
	/// Массив кнопок.
	/// </summary>
        private ButtonExented[,] _buttons;
```

Свойства всегда использую [PascalCasing](https://en.wikipedia.org/wiki/Camel_case).
> Так же если поле protected то оно - должно быть заменено на свойство!

**МОДИФИКАТОР ДОСТУПА НУЖНО УКАЗЫВАТЬ ВСЕГДА**

#

Сдесть не хавает пустых строк, чтобы читать можно было удобнее и форматирование поехало, например `x+= distanceButtons` должно быть `x += distanceButtons` и тд.

https://github.com/kostya-alch/Miner-game/blob/c588266875c843195b753346e66d3720f1fd388e/Miner-game/Form1.cs#L26-L44

#

Опять же нет пустых строк между лбьявлениями методов

https://github.com/kostya-alch/Miner-game/blob/c588266875c843195b753346e66d3720f1fd388e/Miner-game/Form1.cs#L45-L46

#

Почему бы не сократить до

https://github.com/kostya-alch/Miner-game/blob/c588266875c843195b753346e66d3720f1fd388e/Miner-game/Form1.cs#L50-L57

```C#
          if (button.isBomb) Explode(button);
          else EmptyField(button);
```

#

Проблема с форматированием, нет модификатора видисости и доступа (sealed, private/public), нет норм коментария

`public bool isBomb;``` должно быть свойством

https://github.com/kostya-alch/Miner-game/blob/c588266875c843195b753346e66d3720f1fd388e/Miner-game/Form1.cs#L79

```C#
/// <summary>
/// Наследуемый класс, добавляющий к кнопке поле бомбы.
/// </summary>
private sealed class ButtonExented : Button
{
    public bool IsBomb { get; set; }
}
```

**Comment by kostya-alch** [comment]
Всё сделано!
